[package]
name = "cobu_macros"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
syn = "2.0.104"
quote = "1.0.40"
